apiVersion: ENC[AES256_GCM,data:tJs=,iv:w36MwS3ONw7LM4uyyJBVlv6zGFsszZood7CVfnW7hjo=,tag:o3ej5JRPwCJkfqwgzh7wig==,type:str]
kind: ENC[AES256_GCM,data:NIbTh9jX,iv:eIctyPHxo5JWzNoXpEkyj733fl8lY8212SeHENBR4zM=,tag:t7tqfH0kXf98mjJoyZFtFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7uWemZwP6Xb6UNc1hlYE,iv:KP5EjJQMEGrfhX6Ox/pMqwtupmimv4d5IjGThwQssp4=,tag:/WBMnsFmH9EQNubi1uILcA==,type:str]
type: ENC[AES256_GCM,data:f0ypcqjH,iv:WC425oGVR+kp7CagX+WzWfKx+BrSvUGMpbmyafW7jzo=,tag:RCBGKWfK52bPMbkRawf8LQ==,type:str]
data:
    MONGO_DB_CONN_STRING: ENC[AES256_GCM,data:Ka4p1gNAlFhBMar3joH562NBT0tvnYpG4PJncWong6ZxCiPT,iv:W8eJ5YUaTTb3GE3WI2X4SpSxvCrM+1hnRPD35pmmaew=,tag:VTB+DVdrIjzOepH2U+4Omw==,type:str]
    MONGO_DB_NAME: ENC[AES256_GCM,data:Vr2noQCrwOlndX5x+fR2yw==,iv:UqS70SyB3ESBsjUtmrSg+GyMU/Bceko4dltKrvQJm44=,tag:fu63n2QKgLcMk7j86HCiPg==,type:str]
    MONGO_DB_USERNAME: ENC[AES256_GCM,data:ko/6CsYvK6GD+lHj,iv:lQuFsBGYw8d7qeJ6iY6/RBnGS7O28eBFl00CCWqb8dg=,tag:jElDmzQrhpoizt5DsCA1hg==,type:str]
    MONGO_DB_PASSWORD: ENC[AES256_GCM,data:Mj6ZGcOkESJaEbAZk/YU0Z83nY4+tnJL,iv:5pRyLFn6Mpg29p6PJohTUv03NhvLqXI6jm53kZGV/PQ=,tag:9wAe4lzS7zixivM23XtvOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-03T02:23:02Z"
    mac: ENC[AES256_GCM,data:+pP+skNiiExh0aZAfQcaimbovFjJ4z1W6V8yY/rbhyu4/UEE4VDpbTG1vB1aAkr3JevCuxvIikOm7jkRg5mZlVenAvw2sIKRzap9hobr9XPI/uP7//ONzgeKnsXxBgAgVU/xAgmXqsr9b3m7d3gVTCs39nayYt8p+DteBnEQcq0=,iv:OWAJ+JuFEvBsMhQbtDZJ5HX9jnlSAZW1675QJKaEVcc=,tag:4mJlq2gm6LYXeK/Gvc3sGA==,type:str]
    pgp:
        - created_at: "2024-02-03T02:23:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA8Y7sccJP5o2AQv8Dhob7C5dTzj/idfMpxnzx8CKT4W+Cre0G2/ApSoPPnhp
            EyMr4PMdo6zI33h/7js9+1oeSjf240TXMyF9PsfDo6aungBJ1WgRCXMca+QdftKg
            9gEUUqHw1abd6GI95Hx6m82pQvLOE4/BtXIpuoZ+0Z6ekEJqy0oft39vlX4mhlYb
            22lqGjeEhl5FWsaNfvTxpCxx9XKpgNIQLi+TsBF1fP/iH9nUlwTf7AqyKwD+8tPt
            MEgx48EpSy7KN/D5oZPW673/Om7UOfkFJOiP1skSYseh94Q/80r/i70i62pWcI30
            r6L0WAwI3G7Qg5Te7D0eTMk11mclnD74TvR/TUB3O2wh25z68pBoxJ8U6GN0xv65
            T6oXFBx/MYtq475N6P3eahowAzzl3ptXkIhfxa8gmYYKPY45McFwevJnxvVT0P+R
            vl6soXhoa7LqRMqn/G8J1AhgHLYv6hvqmXwoqIyRrpX7jIUna3JLzRHRX2kAuC53
            /N5pmR2/QK5OrIUOD7h90l4B1uagMkhTW45gTNTjMQTtUf3NxXbrKZCgNmV0U5l6
            b1OXgMdiiSyFySFKoa4xg70EhMJaSvbgNLBShYuCV2+zE04ZBf26p4kicDgNQKkX
            bo6tAeCXETo5kV3rh+43
            =wclF
            -----END PGP MESSAGE-----
          fp: 5844006A93C330637AEA4FD4810E0B315B118D1E
    unencrypted_suffix: _unencrypted
    version: 3.8.1
